Repository IshaaqhShaik/JAN_WEB_DEV, pull requests merged in 2024-02, with the labels that each got.

#60 Module 3 day 1
  Module-3/Day1/Cheatsheet/cheatsheet.txt
  Module-3/Day1/Presentation/Html_Intro_p.pdf
  Module-3/Day1/Task/Farooq/index.html
  Module-3/Day1/Task/Haseeb/index.html
  Module-3/Day1/Task/Saddam/index.html
  Module-3/Day1/Task/Task-1.img.jpeg
  Module-3/Day1/Task/Task-2.img.jpeg
  Module-3/Day1/Task/Task-3.img.jpeg
  Module-3/Day1/Task/Task-4.img.jpeg
  Module-3/Day1/Task/Task-5.img.jpeg
Labels: Presenter

#62 Added module-3-day-2
  Module-3/Day2/CheatSheet/cheatSheet.txt
  Module-3/Day2/Presentation/HTML_Tags.pdf
  Module-3/Day2/Task/Farooq/index.html
  Module-3/Day2/Task/Haseeb/index.html
  Module-3/Day2/Task/Saddam/index.html
  Module-3/Day2/Task/Task_imgs/Task-2.png
  Module-3/Day2/Task/Task_imgs/Task-3.1.png
  Module-3/Day2/Task/Task_imgs/Task-3.png
  Module-3/Day2/Task/Task_imgs/Task-4.1.png
  Module-3/Day2/Task/Task_imgs/Task-4.png
  Module-3/Day2/Task/Task_imgs/Task.png
Labels: Presenter

#70 Added module-3-day-4 files and folders
  Module-3/Day4/Cheatsheet/cheatsheet.txt
  Module-3/Day4/Presentation/HTML-TABLES.pdf
  Module-3/Day4/Task/Farooq/index.html
  Module-3/Day4/Task/Haseeb/index.html
  Module-3/Day4/Task/Saddam/index.html
  Module-3/Day4/Task/Task-1.jpeg
  Module-3/Day4/Task/Task-2.jpeg
  Module-3/Day4/Task/Task-3.jpeg
  Module-3/Day4/Task/Task-4.jpeg
  Module-3/Day4/Task/Task-5.jpeg
  Module-3/Day4/Task/Task-6.jpeg
Labels: Presenter

#61 added cheatSheet with Interview Qustion and Answers
  Module-3/Day1/Cheatsheet/cheatsheet.txt
Labels: Sub_Presenter

#69 Day3 folder is created and respective files are added
  Module-3/Day3/CheatSheet/CheatSheet.txt
  Module-3/Day3/Presentation/Module-3-Day-3-ppt.pdf
  Module-3/Day3/Task/Haseeb/index.html
  Module-3/Day3/Task/Saddam/index.html
  Module-3/Day3/Task/applicationform-task5.jpeg
  Module-3/Day3/Task/college-feedback-form-task4.jpeg
  Module-3/Day3/Task/farooq/index.html
  Module-3/Day3/Task/feed-backform-task6.jpeg
  Module-3/Day3/Task/job-details-task3.jpeg
  Module-3/Day3/Task/loan-application-task2.jpeg
  Module-3/Day3/Task/login-task1.jpeg
  Module-3/Day3/Task/student-registration-form-task7.jpeg
Labels: Presenter

#73 Added module-3-day-5 files and folders
  Module-3/Day5/CheatSheet/cheatsheet.txt
  Module-3/Day5/Presentation/Handling Media.pdf
  Module-3/Day5/Task/Farooq/index.html
  Module-3/Day5/Task/Haseeb/index.html
  Module-3/Day5/Task/Saddam/index.html
Labels: Presenter

#80 Module-4-Day-1 respective files are added
  Module-4/Day-1/Cheatsheet/Cheatsheet.txt
  Module-4/Day-1/Presentation/Module-4-Day-1-Ppt.pdf
  Module-4/Day-1/Task/Farooq/index.html
  Module-4/Day-1/Task/Haseeb/index.html
  Module-4/Day-1/Task/Saddam/index.html
Labels: Presenter

#79 added cheatsheet for module-3-day-3
  Module-3/Day3/CheatSheet/CheatSheet.txt
Labels: Sub_Presenter

#81 added module-4-day-2 files and folders
  Module-4/Day-2/Cheatsheet/Cheatsheet.txt
  Module-4/Day-2/Presentation/SHADOWS -ANIMATIONS.pdf
  Module-4/Day-2/Task/Farooq/index.html
  Module-4/Day-2/Task/Haseeb/index.html
  Module-4/Day-2/Task/Saddam/index.html
Labels: Presenter

#83 added module-4-day-3 files and folders
  Module-4/Day-3/CheatSheet/cheatsheet.txt
  Module-4/Day-3/Presentation/HandlingResponsiveness.pdf
  Module-4/Day-3/Task/Farooq/index.html
  Module-4/Day-3/Task/Haseeb/index.html
  Module-4/Day-3/Task/Saddam/index.html
Labels: Presenter

#63 Module 3 day 1 haseeb dev
  .gitignore
  Module-3/Day1/Task/Haseeb/Task_1.html
  Module-3/Day1/Task/Haseeb/Task_2.html
  Module-3/Day1/Task/Haseeb/Task_3.html
  Module-3/Day1/Task/Haseeb/Task_5.html
  Module-3/Day1/Task/Haseeb/assets/icons8-coffee-64.png
  Module-3/Day1/Task/Haseeb/index.html
  Module-3/Day1/Task/Haseeb/task-4.html
Labels: AdminReview

#67 Module 3 day 2 haseeb dev
  Module-3/Day2/Task/Haseeb/about.html
  Module-3/Day2/Task/Haseeb/contact.html
  Module-3/Day2/Task/Haseeb/home.html
  Module-3/Day2/Task/Haseeb/index.html
  Module-3/Day2/Task/Haseeb/index_task_5.html
  Module-3/Day2/Task/Haseeb/join.html
  Module-3/Day2/Task/Haseeb/task_1.html
  Module-3/Day2/Task/Haseeb/task_2.html
  Module-3/Day2/Task/Haseeb/task_3.html
  Module-3/Day2/Task/Haseeb/task_4.1.html
  Module-3/Day2/Task/Haseeb/task_4.html
  Module-3/Day2/Task/Haseeb/terms.html
Labels: AdminReview

#71 Module 3 day 3 haseeb dev
  Module-3/Day3/Task/Haseeb/index.html
  Module-3/Day3/Task/Haseeb/task_1.html
  Module-3/Day3/Task/Haseeb/task_2.html
  Module-3/Day3/Task/Haseeb/task_3.html
  Module-3/Day3/Task/Haseeb/task_4.html
  Module-3/Day3/Task/Haseeb/task_5.html
  Module-3/Day3/Task/Haseeb/task_6.html
  Module-3/Day3/Task/Haseeb/task_7.html
Labels: AdminReview

#85 added module-3-day-4 task's
  Module-3/Day4/Task/Haseeb/task_1.html
  Module-3/Day4/Task/Haseeb/task_2.html
  Module-3/Day4/Task/Haseeb/task_3.html
  Module-3/Day4/Task/Haseeb/task_4.html
  Module-3/Day4/Task/Haseeb/task_5.html
Labels: AdminReview

#76 Updated day 3 tasks
  Module-3/Day3/Task/farooq/task_1.html
  Module-3/Day3/Task/farooq/task_2.html
  Module-3/Day3/Task/farooq/task_3.html
  Module-3/Day3/Task/farooq/task_4.html
  Module-3/Day3/Task/farooq/task_5.html
  Module-3/Day3/Task/farooq/task_6.html
  Module-3/Day3/Task/farooq/task_7.html
Labels: PeerReview

#64 added task files for module-3-day-1
  Module-3/Day1/Task/Saddam/index.html
  Module-3/Day1/Task/Saddam/index2.html
  Module-3/Day1/Task/Saddam/index3.html
  Module-3/Day1/Task/Saddam/index4.html
  Module-3/Day1/Task/Saddam/index5.html
  Module-3/Day1/Task/golden-gate-bridge.png
Labels: AdminReview

#68 added tasks html files for module-3-day-2
  Module-3/Day1/Task/Saddam/index.html
  Module-3/Day2/Task/Saddam/index-task-1.html
  Module-3/Day2/Task/Saddam/index-task-2-6.html
  Module-3/Day2/Task/Saddam/index-task-3.html
  Module-3/Day2/Task/Saddam/index-task-4.1.html
  Module-3/Day2/Task/Saddam/index-task-4.html
  Module-3/Day2/Task/Saddam/index-task-5.html
  Module-3/Day2/Task/Saddam/index.html
Labels: AdminReview

#72 Module 3 day 3 saddam dev
  Module-3/Day3/Task/Saddam/Task-1.html
  Module-3/Day3/Task/Saddam/Task-2.html
  Module-3/Day3/Task/Saddam/Task-3.html
  Module-3/Day3/Task/Saddam/Task-4.html
  Module-3/Day3/Task/Saddam/Task-5.html
  Module-3/Day3/Task/Saddam/Task-6.html
  Module-3/Day3/Task/Saddam/Task-7.html
  Module-3/Day3/Task/Saddam/index.html
Labels: AdminReview

#82 added tasks files for module-4-day-1
  Module-4/Day-1/Task/Saddam/Task-1.html
  Module-4/Day-1/Task/Saddam/Task-2.html
  Module-4/Day-1/Task/Saddam/index.html
Labels: AdminReview

#88 added module-4-day-2 tasks
  Module-4/Day-2/Task/Saddam/Task-1.html
  Module-4/Day-2/Task/Saddam/Task-2.html
  Module-4/Day-2/Task/Saddam/Task-3.html
  Module-4/Day-2/Task/Saddam/index.html
Labels: Changes Requested

#91 Module-4-Day-4 required files are added
  Module-4/Day-4/Cheatsheet/Cheatsheet.txt
  Module-4/Day-4/Presentation/Module-4-Day-4-Grids.pdf
  Module-4/Day-4/Task/Farooq/index.html
  Module-4/Day-4/Task/Haseeb/index.html
  Module-4/Day-4/Task/Saddam/index.html
Labels: Presenter
